<?php

/**
 * @file
 * Allows users to authenticate against an external SAML identity provider.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Component\Utility\UrlHelper;
use Drupal\samlauth\Controller\SamlController;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function samlauth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the samlauth module.
    case 'help.page.samlauth':
      $module_path = \Drupal::moduleHandler()->getModule('samlauth')->getPath();
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows users to authenticate against an external SAML identity provider.') . '</p>';
      $output .= '<p>' . t('Most information on how to configure this module is in the <a href=":url">README.md file</a>.', [':url' => Url::fromUri("base:$module_path/README.md")->toString()]) . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function samlauth_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['#validate'][] = 'samlauth_check_saml_user';
}

/**
 * Validation callback for SAML users logging in through the normal methods.
 */
function samlauth_check_saml_user($form, FormStateInterface $form_state) {
  if (!\Drupal::config('samlauth.authentication')->get('drupal_saml_login')) {
    if ($form_state->hasAnyErrors()) {
      // If previous validation has already failed (name/pw incorrect or blocked
      // ), bail out so we don't disclose any details about a user that otherwi-
      // se wouldn't be authenticated.
      return;
    }

    // If the user has logged into the site using samlauth before, block them.
    // (There is no option to disallow _any_ user from logging in locally;
    // that's not considered the business of this module.) Account for modules
    // that change the login form, only in the sense that we check whether the
    // 'name' element actually exists. If modules change the login form (by
    // e.g. having a 'mail' element instead, or having the 'name' field contain
    // an e-mail address) and need this blocking to work (differently), that
    // should be solved by a custom module to make both work together. (Or a
    // well thought out suggestion in the issue queue.)
    if ($form_state->hasValue('name') && $account = user_load_by_name($form_state->getValue('name'))) {
      /** @var \Drupal\externalauth\AuthmapInterface $authmap */
      $authmap = \Drupal::service('externalauth.authmap');
      $saml_id = $authmap->get($account->id(), 'samlauth');
      if ($saml_id !== FALSE) {
        $form_state->setErrorByName('name', t('SAML users must sign in with SSO'));
      }
    }
  }
}

/**
 * Implements hook_user_presave().
 */
function samlauth_user_presave(UserInterface $account) {
  // Hook into the user creation process from ExternalAuth::register() so that
  // we don't need to save the new user a second time to add our SAML attribute
  // values into the new user object. The way externalauth prefixes account
  // names acts as a recursion stop, in case any called code (e.g. event) saves
  // the account.
  if ($account->isNew() && strpos($account->getAccountName(), 'samlauth_') === 0) {
    // Doublecheck that we're actually processing an ACS request, which we can
    // do by checking the request for presence of a user name attribute.
    /** @var \Drupal\samlauth\SamlService $saml_service */
    $saml_service = \Drupal::service('samlauth.saml');
    if ($saml_service->getAttributeByConfig('user_name_attribute')) {
      $saml_service->synchronizeUserAttributes($account, TRUE);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For users that have been authenticated via SAML, hide the user password
 * change field and provide a notice to the user about the user change service.
 *
 * @see https://www.drupal.org/project/samlauth/issues/3185846
 */
function samlauth_form_user_form_alter(&$form, FormStateInterface $form_state) {
  if (\Drupal::config(SamlController::CONFIG_OBJECT_NAME)->get('drupal_saml_login')) {
    return;
  }

  $account = $form_state->getBuildInfo()['callback_object']->getEntity();

  /** @var \Drupal\externalauth\AuthmapInterface $authmap */
  $authmap = \Drupal::service('externalauth.authmap');
  $saml_id = $authmap->get($account->id(), 'samlauth');

  // Only affect SAML authenticated users.
  if ($saml_id !== FALSE) {
    // Hide the change password field.
    $form['account']['pass']['#access'] = FALSE;

    // Display a notice with a link to the proper IdP password change service.
    $idp_change_password_service_url = \Drupal::config(SamlController::CONFIG_OBJECT_NAME)->get('idp_change_password_service');

    // Since the IdP change password service URL is optional, only display the
    // notice if one has been set.
    if (UrlHelper::isValid($idp_change_password_service_url, TRUE)) {
      $form['account']['saml_notice'] = [
        '#markup' => t(
          '<strong>NOTE:</strong> E-mail address and password are controlled via SAML. Please visit <a href="@link">this link</a> to change.',
          ['@link' => $idp_change_password_service_url]
        ),
        '#weight' => -1,
      ];
    }
  }
}
