<?php

use phpseclib3\Crypt\Common\PrivateKey;
use phpseclib3\Crypt\Common\PublicKey;
use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Crypt\RSA;
use phpseclib3\Exception\NoKeyLoadedException;
use phpseclib3\File\X509;

/**
 * @file
 * Helper functions for the key_asymmetric module.
 */

/**
 * Extracts properties from a key/certificate, if it has a known format.
 *
 * Warning: this is potentially very expensive.
 *
 * This would ideally be part of the Key entity (maybe?) - by having code call
 * OurKeyEntity::create() which would (optionally) set all the values from the
 * return value set in key_type_settings of the created entity. For that, we'd
 * need a custom entity subclass for public/private keys, which would require a
 * change to the Key module itself: implementing a custom storage handler for
 * the Key entity type, which enables using different classes for different
 * key types (making mapFromStorageRecords() dynamic in some yet-unknown way).
 * It's too early for that.
 *
 * @param string $key_value
 *   The key (as a string, not an entity) in a format that is recognized by
 *   the phpseclib library.
 * @param string $password
 *   (Optional) password for a password-protected private key
 *
 * @return array
 *   Array with the following keys (which are not necessarily all present):
 *   - type:        "private" / "public"
 *   - format:      format, e.g. "PKCS8"
 *   - key_size:    key size in bits
 *   - algo:        encryption algo, e.g. "RSA"
 *   - hash_algo:   hashing algo, e.g. "sha256" (not sure why lowercase)
 *   - comment:     non-empty comment
 *   - fingerprint: fingerprint for public key
 *   - has_public:  TRUE/FALSE indicating whether this private key has its
 *                  public key included
 *   - cert:
 *     - subject:    (string formatted like "C=<..>, ST=<...>, L=<...>, O=<...>, OU=<...>, CN=<name>/emailAddress=<email>")
 *     - issuer:     (same)
 *     - not_before: (date in unambiguous string notation, UTC)
 *     - not_after:  (same)
 *     - validity:   (would only be set if not_before/not_after are not
 *                   recognized)
 *
 * @throws \RuntimeException
 *   If the input string is not recognized as a key.
 */
function key_asymmetric_get_key_properties($key_value, $password = false) {
  if (empty($key_value)) {
    throw new NoKeyLoadedException('Key is empty.');
  }

  // PublicKeyLoader::load() is generic and slow: it iterates over every
  // known format (MSBLOB, OpenSSH, PKCS1, PKCS*, Putty) for every known
  // encryption algorithm (EC, RSA, DSA), trying to interpret the key in all
  // those formats repeatedly until one works. In the case of public
  // certificates, all those methods fail, after which it tries loadX509(),
  // fetches the key and throws the cert away. Let's optimize for what we
  // think is our most common use case and first try that one (OpenSSL \
  // generated keys, whose default is RSA/PKCS8).
  $key = $cert = FALSE;
  try {
    // We can only try a combination of a specific encryption method + format:
    // AsymmetricKey::loadFormat('PKCS8') doesn't work because properties are
    // not initialized.
    $key = RSA::loadFormat('PKCS8', $key_value, $password);
  }
  catch (\Exception $e) {
  }
  if (!$key) {
    // OpenSSL certs are probably less commmonly stored by the Key module
    // than keys, but since all certs are way at the end of the queue and we
    // can immediately recognize their algorithm/format without having to try
    // a dozen times, let's also prioritize them. loadX509() doesn't seem to
    // ever throw exceptions but still, try/catch.
    try {
      $x509 = new X509();
      $cert = $x509->loadX509($key_value);
    }
    catch (\Exception $e) {
    }
    // The following two key-load methods fall through if they throw an
    // exception. If we have a cert, we don't need to try the generic load()
    // if getPublicKey() throws an exception.
    if ($cert) {
      $key = $x509->getPublicKey();
    }
    else {
      $key = PublicKeyLoader::load($key_value, $password);
    }
  }

  $properties = [];
  if ($key) {
    if ($key instanceof PrivateKey) {
      $properties['type'] = 'private';
    }
    elseif ($key instanceof PublicKey) {
      $properties['type'] = 'public';
    }
    if (is_callable([$key, 'getPublicKey'])) {
      try {
        $properties['has_public'] = !empty($key->getPublicKey());
      }
      catch (\Exception $e) {
        $properties['has_public'] = FALSE;
      }
    }
    if (defined(get_class($key) . '::ALGORITHM')) {
      $properties['algo'] = $key::ALGORITHM;
    }
    if (is_callable([$key, 'getHash'])) {
      $properties['hash_algo'] = $key->getHash()->getHash();
      $properties['hash_size'] = $key->getHash()->getLength();
    }
    foreach ([
               'key_size' => 'getLength',
               'format' => 'getLoadedFormat',
               'comment' => 'getComment',
               'fingerprint' => 'getFingerprint',
             ] as $property_name => $method) {
      if (is_callable([$key, $method])) {
        try {
          // At least getComment can be FALSE. For now we assume we don't
          // have any empty values.
          $value = $key->$method();
          if ($value) {
            $properties[$property_name] = $value;
          }
        }
        catch (\Exception $e) {
        }
      }
    }

    if ($cert && ($properties['type'] ?? NULL) === 'public') {
      // Subject / Issuer are a deep array and we have helper functions to
      // make them into a string. For validity we apparently don't.
      $properties['cert']['subject'] = $x509->getSubjectDN(X509::DN_STRING);
      $properties['cert']['issuer'] = $x509->getSubjectDN(X509::DN_STRING);
      if (isset($cert['tbsCertificate']['validity'])) {
        $validity = $cert['tbsCertificate']['validity'];
        if (isset($validity['notAfter']['utcTime'])
          && is_string($validity['notAfter']['utcTime'])
          && count($validity['notAfter']) == 1
          && (isset($validity['notBefore']['utcTime'])
            ? is_string($validity['notBefore']['utcTime'])
            && count($validity['notBefore']) == 1
            && count($validity) == 2
            : count($validity) == 1)) {
          if (isset($validity['notBefore']['utcTime'])) {
            $properties['cert']['not_before'] = $validity['notBefore']['utcTime'];
          }
          $properties['cert']['not_after'] = $validity['notAfter']['utcTime'];
        }
        else {
          // Format doesn't match our assumptions: be lazy about it, without
          // missing info. Not HTML safe, and callers shouldn't assume that.
          $properties['cert']['validity'] = function_exists('json_encode')
            ? json_encode($validity) : var_export($validity, TRUE);
        }
      }
    }
  }

  return $properties;
}

