<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function samlauth_user_fields_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the samlauth module.
    case 'samlauth_user_fields.list':
      $output = '';
      $output .= '<p>' . t('At this moment, you need to know all SAML attribute names in order to be able to input them in the "Add mapping" screen. This is possible, among others, by inspecting SAML messages logged in the "Recent log messages", after enabling "Log incoming SAML messages".') . '</p>';
      $output .= '<p>' . t('Any number in the "Use for linking" column (including 0) represents an action if the login data (SAML assertion) is not linked to an existing Drupal user yet: an attempt is made at matching the value(s) in the SAML attributes to an existing Drupal user. Attempts are made using the values/fields in increasing order of the numbers; if any user matches, that user is linked to the SAML login. If multiple mappings have the same number, both values must match the corresponding fields. (Matching is only done if all corresponding SAML attributes actually have a value.) These match attempts are done before before trying to match on name or email address (as configured in the main configuration screen), and happen independently of the "Attempt to link SAML data to existing local users" configuration value.') . '</p>';
      return $output;

    default:
  }
}